/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseAdminWorkArea;

import Business.Constants;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.GovernmentEnterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.InsuranceEnterprise;
import Business.Enterprise.WomanEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author praty
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateOrganizationJPanel
     */
    JPanel userProcessContainer;
    //EcoSystem system;
    private Enterprise enterprise;
    private Network network;
    private Organization organization;
    private OrganizationDirectory directory;
    
    public ManageOrganizationJPanel() {
        initComponents();
    }

    public ManageOrganizationJPanel(JPanel userProcessContainer, Enterprise enterprise, Network network , Organization organization, OrganizationDirectory directory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        //this.enterprise = enterprise;
        this.network = network;
        this.organization = organization;
        if(enterprise instanceof GovernmentEnterprise)
        {
            this.enterprise =(GovernmentEnterprise) enterprise;
        }
        else if (enterprise instanceof HospitalEnterprise)
        {
            this.enterprise=(HospitalEnterprise) enterprise;
        }
         else if (enterprise instanceof InsuranceEnterprise)
        {
            this.enterprise=(InsuranceEnterprise) enterprise;
        } else if (enterprise instanceof WomanEnterprise)
        {
            this.enterprise = (WomanEnterprise) enterprise;
        } else if (enterprise instanceof PharmacyEnterprise)
        {
            this.enterprise = (PharmacyEnterprise) enterprise;
        }
       
        this.directory = directory;
        populateOrganizationType();
        populateNetworkEnterpriseTable();
        populateOrganizationTable();
    }
     
    public void populateOrganizationType(){
       // public void populateOrganizationType(){
        /*dropdown_OrganizationType.removeAllItems();
        dropdown_OrganizationType.addItem("--Select--");
        for (Organization.Type type : Organization.Type.values()) {
            dropdown_OrganizationType.addItem(type.getValue());
        }*/
        dropdown_OrganizationType.removeAllItems();
        
        for (Organization.Type type : enterprise.getSupportedOrganizationType()){
                dropdown_OrganizationType.addItem(type);
        }
    }
    
   private void populateNetworkEnterpriseTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_Network_Enterprise.getModel();
        
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
        }
        model.setRowCount(0);
        Object[] row = new Object[model.getColumnCount()];
        row[0] = network;
        row[1] = network.getLocation();
        row[2] = enterprise;
        row[3] = enterprise.getEnterpriseType().getValue();
        model.addRow(row);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
      
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_Network_Enterprise = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Organization = new javax.swing.JTable();
        dropdown_OrganizationType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tbl_Network_Enterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network Name", "Network Location", "Enterprise Name", "Enterprise Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_Network_Enterprise);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tbl_Organization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization ID", "Organization Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Organization);

        dropdown_OrganizationType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Organization Type");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/Save-as-icon.png"))); // NOI18N
        btnSave.setText("Add");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/Go-back-icon.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(46, 46, 46)
                        .addComponent(dropdown_OrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(507, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdown_OrganizationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnBack))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Manage Organization");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
         if(dropdown_OrganizationType.getSelectedItem().toString().equals("Admin") && directory.duplicateOrg(Organization.Type.Admin.getValue()) == false){
           //organization = enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Admin);
           directory.createOrganization(Organization.Type.Admin);
       } else if(dropdown_OrganizationType.getSelectedItem().toString().equals("Claims") && directory.duplicateOrg(Organization.Type.Claims.getValue()) == false ){
           //organization = enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Claims);
           directory.createOrganization(Organization.Type.Claims);
       } else if(dropdown_OrganizationType.getSelectedItem().toString().equals("Doctor") && directory.duplicateOrg(Organization.Type.Doctor.getValue())== false ){
           //organization = enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Doctor);
           directory.createOrganization(Organization.Type.Doctor);
       } else if(dropdown_OrganizationType.getSelectedItem().toString().equals("Lab") && directory.duplicateOrg(Organization.Type.Lab.getValue())== false ){
           //organization = enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Lab);
           directory.createOrganization(Organization.Type.Lab);
       } else if(dropdown_OrganizationType.getSelectedItem().toString().equals("Ministry") && directory.duplicateOrg(Organization.Type.Ministry.getValue())== false ){
           //organization = enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Ministry);
           directory.createOrganization(Organization.Type.Ministry);
       } else if(dropdown_OrganizationType.getSelectedItem().toString().equals("NGO") && directory.duplicateOrg(Organization.Type.NGO.getValue()) == false ){
           //organization = enterprise.getOrganizationDirectory().createOrganization(Organization.Type.NGO);
           directory.createOrganization(Organization.Type.NGO);
       }else if(dropdown_OrganizationType.getSelectedItem().toString().equals("Nurse") && directory.duplicateOrg(Organization.Type.Nurse.getValue()) == false ){
           //organization = enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Nurse);
           directory.createOrganization(Organization.Type.Nurse);
       }else if(dropdown_OrganizationType.getSelectedItem().toString().equals("Woman") && directory.duplicateOrg(Organization.Type.Woman.getValue()) == false){
           //organization = enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Patient);
           directory.createOrganization(Organization.Type.Woman);
       }else if(dropdown_OrganizationType.getSelectedItem().toString().equals("Pharmacy") && directory.duplicateOrg(Organization.Type.Pharmacy.getValue()) == false ){
           //organization = enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Pharmacy);
           directory.createOrganization(Organization.Type.Pharmacy);
       }else if(dropdown_OrganizationType.getSelectedItem().toString().equals("PolicyIssue") && directory.duplicateOrg(Organization.Type.PolicyIssue.getValue()) == false ){
           //organization = enterprise.getOrganizationDirectory().createOrganization(Organization.Type.PolicyIssue);
           directory.createOrganization(Organization.Type.PolicyIssue);
       }else if(dropdown_OrganizationType.getSelectedItem().toString().equals("Receptionist") && directory.duplicateOrg(Organization.Type.Receptionist.getValue()) == false ){
           //organization = enterprise.getOrganizationDirectory().createOrganization(Organization.Type.Receptionist);
           directory.createOrganization(Organization.Type.Receptionist);
       }else {
           JOptionPane.showMessageDialog(null, "Please select Organization Type");
       } 
        JOptionPane.showMessageDialog(null, "Organization is Created Succesfully");
        populateOrganizationTable();
        populateOrganizationType();  
       Organization.Type type = (Organization.Type) dropdown_OrganizationType.getSelectedItem();
      
       if(directory.duplicateOrg(type.getValue())== true){
            JOptionPane.showMessageDialog(null, "Organization already exists");
        }else{
            JOptionPane.showMessageDialog(null, "Organization is Created Succesfully");
            directory.createOrganization(type);
            populateOrganizationTable();
        } 
    }//GEN-LAST:event_btnSaveActionPerformed

     private void populateOrganizationTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_Organization.getModel();

        for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
        }
        for (Organization organization : directory.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }
     
     
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox dropdown_OrganizationType;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Panel panel1;
    private javax.swing.JTable tbl_Network_Enterprise;
    private javax.swing.JTable tbl_Organization;
    // End of variables declaration//GEN-END:variables
}
