/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WomanRole;

import Business.Employee.Employee;
import UserInterface.DoctorRole.*;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.Organization.WomanOrganization;
import Business.Organization.ReceptionistOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.PatientAppointmentRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author prima
 */
public class WomanRequestAppointmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorRequestLabTestJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    private UserAccount userAccount;
    private WomanOrganization organization;
    
    public WomanRequestAppointmentJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, WomanOrganization organization,Network network) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.organization = organization;
        this.network= network;
        populateHospital();
       
    }
    
    public void populateHospital(){
        txtHospital.removeAllItems();
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()){
            if (ent instanceof HospitalEnterprise){
                txtHospital.addItem(ent.getName());
            }
        }
    }
    
    
     private boolean Validate(){
         
       
        Pattern pattern = Pattern.compile("^[a-zA-Z0-9_!#$%&’*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$");
        Matcher matcher = pattern.matcher(txt_email.getText());

        
        boolean b = matcher.find();
        if(b==true){
            return false;
        }
        else{
            return true;
        }
    }
     
     private boolean Validate2(){
         
       
        Pattern pattern = Pattern.compile("^[a-zA-Z0-9_!#$%&’*+/=?`{|}~^.-]+@[a-zA-Z0-9.-]+$");
        Matcher matcher = pattern.matcher(txtEEmail.getText());

        
        boolean b = matcher.find();
        if(b==true){
            return false;
        }
        else{
            return true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_Name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txtHospital = new javax.swing.JComboBox<>();
        lbl_Reason = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_Age = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnRequest = new javax.swing.JButton();
        txtlastname = new javax.swing.JTextField();
        txtContactNum = new javax.swing.JTextField();
        lbl_Email1 = new javax.swing.JLabel();
        lbl_Email2 = new javax.swing.JLabel();
        lbl_Reason1 = new javax.swing.JLabel();
        lbl_Name1 = new javax.swing.JLabel();
        lbl_Name2 = new javax.swing.JLabel();
        lbl_Name3 = new javax.swing.JLabel();
        lbl_Reason2 = new javax.swing.JLabel();
        lbl_Name4 = new javax.swing.JLabel();
        lbl_Name5 = new javax.swing.JLabel();
        lbl_Reason3 = new javax.swing.JLabel();
        lbl_Name6 = new javax.swing.JLabel();
        lbl_Reason4 = new javax.swing.JLabel();
        lbl_Reason5 = new javax.swing.JLabel();
        lbl_Reason6 = new javax.swing.JLabel();
        lbl_Name7 = new javax.swing.JLabel();
        lbl_Age1 = new javax.swing.JLabel();
        lbl_Email3 = new javax.swing.JLabel();
        lbl_Email4 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        txtZip = new javax.swing.JTextField();
        txtInsuranceProvider = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtMedID = new javax.swing.JTextField();
        txtAllergies = new javax.swing.JTextField();
        txtEFirstName = new javax.swing.JTextField();
        txtELastName = new javax.swing.JTextField();
        txtEEmail = new javax.swing.JTextField();
        txtEContact = new javax.swing.JTextField();
        txtTime = new javax.swing.JComboBox();
        txtDate = new com.toedter.calendar.JDateChooser();
        Combo_disease = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        panel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Woman Request Appointment");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lbl_Name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Name.setText("First Name");

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });

        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });

        txtHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        txtHospital.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHospitalMouseClicked(evt);
            }
        });
        txtHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalActionPerformed(evt);
            }
        });

        lbl_Reason.setText("Reason for appointment");

        lbl_Email.setText("Age");

        lbl_Age.setText("Last Name");

        jLabel1.setText("Hospital");

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/Go-back-icon.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRequest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/Save-as-icon.png"))); // NOI18N
        btnRequest.setText("Request Appointment");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        txtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlastnameActionPerformed(evt);
            }
        });

        txtContactNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNumActionPerformed(evt);
            }
        });

        lbl_Email1.setText("Email address");

        lbl_Email2.setText("Contact Number");

        lbl_Reason1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Reason1.setForeground(new java.awt.Color(0, 153, 153));
        lbl_Reason1.setText("Address");

        lbl_Name1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Name1.setText("Street");

        lbl_Name2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Name2.setText("City");

        lbl_Name3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Name3.setText("Zip Code");

        lbl_Reason2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Reason2.setForeground(new java.awt.Color(0, 153, 153));
        lbl_Reason2.setText("Insurance Details");

        lbl_Name4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Name4.setText("Member ID");

        lbl_Name5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Name5.setText("Insurance Provider");

        lbl_Reason3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Reason3.setForeground(new java.awt.Color(0, 153, 153));
        lbl_Reason3.setText("Emergency Contact Details");

        lbl_Name6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Name6.setText("Allergies (If any)");

        lbl_Reason4.setText("Preferred Time");

        lbl_Reason5.setText("Preferred Date");

        lbl_Reason6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_Reason6.setForeground(new java.awt.Color(0, 153, 153));
        lbl_Reason6.setText("Medical Details");

        lbl_Name7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_Name7.setText("First Name");

        lbl_Age1.setText("Last Name");

        lbl_Email3.setText("Email address");

        lbl_Email4.setText("Contact Number");

        txtStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetActionPerformed(evt);
            }
        });

        txtZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtZipActionPerformed(evt);
            }
        });

        txtInsuranceProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsuranceProviderActionPerformed(evt);
            }
        });

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        txtMedID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedIDActionPerformed(evt);
            }
        });

        txtAllergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAllergiesActionPerformed(evt);
            }
        });

        txtEFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEFirstNameActionPerformed(evt);
            }
        });

        txtELastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtELastNameActionPerformed(evt);
            }
        });

        txtEEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEEmailActionPerformed(evt);
            }
        });

        txtEContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEContactActionPerformed(evt);
            }
        });

        txtTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a preferred time slot", "Morning: 8:00 AM - 12:00 PM", "Afternoon: 12:00 PM - 4:00 PM", "Evening: 4:00 PM - 8:00 PM" }));

        Combo_disease.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Breast Cancer", "Cervical Cancer", "Depression and Anxiety", "Heart Problem" }));
        Combo_disease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_diseaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_Email2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbl_Name7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_Age1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_Email3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_Email4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnBack)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtELastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtEContact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnRequest, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_Reason1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Reason, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Name3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Reason2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Name4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Name5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Name6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Reason4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Reason5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Reason6, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtHospital, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtStreet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtZip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtInsuranceProvider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMedID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAllergies, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTime, 0, 302, Short.MAX_VALUE)
                                        .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_Reason3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 235, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtContactNum, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txt_age, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtlastname, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(Combo_disease, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Name)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Age)
                    .addComponent(txtlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Email)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Email1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Email2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Reason)
                    .addComponent(Combo_disease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Reason5)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Reason4)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_Reason1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Name1)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Name2)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Name3)
                    .addComponent(txtZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_Reason2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Name4)
                    .addComponent(txtMedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Name5)
                    .addComponent(txtInsuranceProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(lbl_Reason6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Name6)
                    .addComponent(txtAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_Reason3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Name7)
                    .addComponent(txtEFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Age1)
                    .addComponent(txtELastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Email3))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Email4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequest)
                    .addComponent(btnBack))
                .addGap(0, 191, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(panel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtHospitalActionPerformed

    private void txtHospitalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHospitalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalMouseClicked

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
       
          if(txt_name.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Enter First Name");
                return;
            } 
         if(txtlastname.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Enter Last Name");
                return;
            } 
         if(txt_age.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Enter Age");
                return;
            } 
          if(txt_email.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Enter Email Address");
                return;
            } 
           if(txtContactNum.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Enter Phone Number");
                return;
            } 
             if(txtDate.toString().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Enter Preferred Date");
                return;
            } 
           if(txtStreet.getText().isEmpty())
           {
            JOptionPane.showMessageDialog(null,"Enter Street");
           }
           
           if(txtCity.getText().isEmpty())
           {
            JOptionPane.showMessageDialog(null,"Enter City");
           }
         if(txtZip.getText().isEmpty())
           {
            JOptionPane.showMessageDialog(null,"Enter Zip");
           }
         if(txtMedID.getText().isEmpty())
           {
            JOptionPane.showMessageDialog(null,"Enter Member ID");
           }
          if(txtInsuranceProvider.getText().isEmpty())
           {
            JOptionPane.showMessageDialog(null,"Enter Insurance Provider");
           }
          if(txtEFirstName.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Enter Emergency Contact First Name");
                return;
            } 
         if(txtELastName.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Enter Emergency Contact Last Name");
                return;
            } 
         if(txtEEmail.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Enter Emergency Contact Email");
                return;
            } 
          if(txtEContact.getText().isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Enter Emergency Contact Number");
                return;
            } 
          
         
        if(Validate()){
            JOptionPane.showMessageDialog(this,"Enter Email Address in Correct Format ");
            return;
        }
        
         
        if(Validate2()){
            JOptionPane.showMessageDialog(this,"Enter Emergency Contact Email Address in Correct Format ");
            return;
        }
        
        
        
        
        
        
        
        
        
          if(Validate()){
            JOptionPane.showMessageDialog(this,"Enter Email Address in Correct Format ");
            return;
        }
        
        
        
        
        String message = Combo_disease.getSelectedItem().toString();
        String firstname = txt_name.getText();
        String lastname = txtlastname.getText();
        String age = txt_age.getText();
        String email = txt_email.getText();
        String contactnum = txtContactNum.getText();
        String date = txtDate.getDateFormatString().toString();
        String time = txtTime.getSelectedItem().toString();
        String hospital = txtHospital.getSelectedItem().toString();
        String street = txtStreet.getText();
        String city = txtCity.getText();
        String zip = txtZip.getText();
        String medid = txtMedID.getText();
        String insuranceprovider = txtInsuranceProvider.getText();
        String allergies = txtAllergies.getText();
        String efirstname = txtEFirstName.getText();
        String elastname = txtELastName.getText();
        String eemail = txtEEmail.getText();
        String econtactnum = txtEContact.getText();
        
        

        PatientAppointmentRequest request = new PatientAppointmentRequest();
        request.setMessage(message);
        request.setFirstName(firstname);
        request.setLastName(lastname);
        request.setAge(age);
        request.setEmailAddress(email);
        request.setContact(contactnum);
        request.setDate(date);
        request.setTime(time);
        request.setHospital(hospital);
        request.setStreet(street);
        request.setCity(city);
        request.setZipCode(zip);
        request.setMemberId(medid);
        request.setInsuranceProvider(insuranceprovider);
        request.setAllergy(allergies);
        request.seteFirstName(efirstname);
        request.seteLastName(elastname);
        request.seteEmailAddress(eemail);
        request.seteContact(econtactnum);
        
        
        request.setSender(userAccount);
        request.setStatus("Received");
        request.setAge(txt_age.getText());

        Enterprise ent =null;
        Organization org = null;
        
        for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){
            if(txtHospital.getSelectedItem().toString().equals(enterprise.getName())){
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
                    if (organization instanceof ReceptionistOrganization){
                        org = organization;
                        break;
                    }
                }
            }

        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            organization.getWorkQueue().getWorkRequestList().add(request);
        }
        
                JOptionPane.showMessageDialog(this, "Appointment Request Submitted Successfully!");

    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        WomanWorkAreaJPanel dwjp = (WomanWorkAreaJPanel) component;
        dwjp.populateAppointmentRequestTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlastnameActionPerformed

    private void txtContactNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNumActionPerformed

    private void txtStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetActionPerformed

    private void txtZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtMedIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedIDActionPerformed

    private void txtAllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAllergiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAllergiesActionPerformed

    private void txtEFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEFirstNameActionPerformed

    private void txtELastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtELastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtELastNameActionPerformed

    private void txtEEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEEmailActionPerformed

    private void txtEContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEContactActionPerformed

    private void txtInsuranceProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsuranceProviderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsuranceProviderActionPerformed

    private void Combo_diseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_diseaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_diseaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Combo_disease;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Age;
    private javax.swing.JLabel lbl_Age1;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Email1;
    private javax.swing.JLabel lbl_Email2;
    private javax.swing.JLabel lbl_Email3;
    private javax.swing.JLabel lbl_Email4;
    private javax.swing.JLabel lbl_Name;
    private javax.swing.JLabel lbl_Name1;
    private javax.swing.JLabel lbl_Name2;
    private javax.swing.JLabel lbl_Name3;
    private javax.swing.JLabel lbl_Name4;
    private javax.swing.JLabel lbl_Name5;
    private javax.swing.JLabel lbl_Name6;
    private javax.swing.JLabel lbl_Name7;
    private javax.swing.JLabel lbl_Reason;
    private javax.swing.JLabel lbl_Reason1;
    private javax.swing.JLabel lbl_Reason2;
    private javax.swing.JLabel lbl_Reason3;
    private javax.swing.JLabel lbl_Reason4;
    private javax.swing.JLabel lbl_Reason5;
    private javax.swing.JLabel lbl_Reason6;
    private java.awt.Panel panel1;
    private javax.swing.JTextField txtAllergies;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContactNum;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtEContact;
    private javax.swing.JTextField txtEEmail;
    private javax.swing.JTextField txtEFirstName;
    private javax.swing.JTextField txtELastName;
    private javax.swing.JComboBox<String> txtHospital;
    private javax.swing.JTextField txtInsuranceProvider;
    private javax.swing.JTextField txtMedID;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JComboBox txtTime;
    private javax.swing.JTextField txtZip;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txtlastname;
    // End of variables declaration//GEN-END:variables
}
