/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NetworkAdminWorkArea;

import Business.Constants;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author praty
 */
public class CreateEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateEnterpriseJPanel
     */
    JPanel userProcessContainer;
    Network network;
    Enterprise enterprise;
    EcoSystem system;
    public CreateEnterpriseJPanel() {
        initComponents();
    }
    
    CreateEnterpriseJPanel(JPanel userProcessContainer,Network network,EcoSystem system ) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
       this.network = network;
       this.system = system;
       populateNetworkTable();
       PopulateEnterpriseType();
       PopulateEnterpriseTable();
    }
    
    public void PopulateEnterpriseType(){
        DropdownEnterpriseType.removeAllItems();
        DropdownEnterpriseType.addItem("--Select--");
        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            DropdownEnterpriseType.addItem(type.getValue());
        }
    }
    
    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_Network.getModel();

        model.setRowCount(0);
        Object[] row = new Object[model.getColumnCount()];
        row[0] = network;
        row[1] = network.getLocation();
        model.addRow(row);
        
    }
    
    public void PopulateEnterpriseTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_Enterprise.getModel();

        model.setRowCount(0);
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            for(UserAccount useracount : enterprise.getUserAccountDirectory().getUserAccountList()){
                Object[] row = new Object[model.getColumnCount()];
                row[0] = enterprise;
                row[1] = enterprise.getEnterpriseType().getValue();
                row[2] = useracount.getEmployee().getName();
                row[3] = useracount;
                model.addRow(row);
            }
            if(enterprise.getUserAccountDirectory().getUserAccountList().isEmpty()){
                Object[] row = new Object[model.getColumnCount()];
                row[0] = enterprise;
                row[1] = enterprise.getEnterpriseType().getValue();
                row[2] = "";
                row[3] = "";
                model.addRow(row);
            }
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Network = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabelEnterpriseName = new javax.swing.JLabel();
        jLabelEnterpriseType = new javax.swing.JLabel();
        txt_EnterpriseName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnaddEnterpriseAdmin = new javax.swing.JButton();
        DropdownEnterpriseType = new javax.swing.JComboBox<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Enterprise = new javax.swing.JTable();
        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tbl_Network.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Network Name", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Network);

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/Go-back-icon.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabelEnterpriseName.setText("Enterprise Name");

        jLabelEnterpriseType.setText("Enterprise Type");

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/Save-as-icon.png"))); // NOI18N
        btnSave.setText("Add");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnaddEnterpriseAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnaddEnterpriseAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/add-user-icon.png"))); // NOI18N
        btnaddEnterpriseAdmin.setText("Add Enterprise Admin");
        btnaddEnterpriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddEnterpriseAdminActionPerformed(evt);
            }
        });

        DropdownEnterpriseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbl_Enterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Enterprise Type", "Enterprise UserName", "Enterprise UserId"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_Enterprise);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSave)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelEnterpriseName)
                                        .addComponent(jLabelEnterpriseType))
                                    .addGap(28, 28, 28)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DropdownEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_EnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnaddEnterpriseAdmin))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnterpriseName)
                    .addComponent(txt_EnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEnterpriseType)
                    .addComponent(DropdownEnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddEnterpriseAdmin)
                    .addComponent(btnBack))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        panel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create Enterprise");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       if (txt_EnterpriseName.getText().equals("")) {
            JOptionPane.showMessageDialog(null, Constants.EnterpriseName_valmsg, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }else if (DropdownEnterpriseType.getSelectedItem().toString().equals("")) {
            JOptionPane.showMessageDialog(null, Constants.Enterprise_type, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            if(network.checkIfEnterpriseIsUnique(txt_EnterpriseName.getText(), DropdownEnterpriseType.getSelectedItem().toString()) == false){
                JOptionPane.showMessageDialog(null, "Enterprise information already exists", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                if(DropdownEnterpriseType.getSelectedItem().toString().equals("Government")){
                    enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(txt_EnterpriseName.getText(), Enterprise.EnterpriseType.Government);
                } else if(DropdownEnterpriseType.getSelectedItem().toString().equals("Hospital")){
                    enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(txt_EnterpriseName.getText(), Enterprise.EnterpriseType.Hospital);
                } else if(DropdownEnterpriseType.getSelectedItem().toString().equals("Woman")){
                    enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(txt_EnterpriseName.getText(), Enterprise.EnterpriseType.Woman);
                } else if(DropdownEnterpriseType.getSelectedItem().toString().equals("Insurance")){
                    enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(txt_EnterpriseName.getText(), Enterprise.EnterpriseType.Insurance);
                } else if(DropdownEnterpriseType.getSelectedItem().toString().equals("Pharmacy")){
                    enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(txt_EnterpriseName.getText(), Enterprise.EnterpriseType.Pharmacy);
                } else {
                    JOptionPane.showMessageDialog(null, "Please select EnterpriseType");
                }
                JOptionPane.showMessageDialog(null, "Enterprise is Created Succesfully");
                PopulateEnterpriseTable();
                txt_EnterpriseName.setText("");
                PopulateEnterpriseType();
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnaddEnterpriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddEnterpriseAdminActionPerformed
         int selectedRow = tbl_Enterprise.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select any row from Enterprise table", "Error", JOptionPane.ERROR_MESSAGE);
        } else
        {
            Enterprise enterprise = (Enterprise)tbl_Enterprise.getValueAt(selectedRow, 0);
            if(enterprise.getUserAccountDirectory().getUserAccountList().isEmpty()){
                CreateEnterpriseAdminJPanel CreateEnterpriseAdmin = new CreateEnterpriseAdminJPanel(userProcessContainer, enterprise, system);
                userProcessContainer.add("CreateEnterpriseAdminJPanel", CreateEnterpriseAdmin);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }else{
                JOptionPane.showMessageDialog(null, "Admin Already Present for selected row.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
        
    }//GEN-LAST:event_btnaddEnterpriseAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DropdownEnterpriseType;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnaddEnterpriseAdmin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEnterpriseName;
    private javax.swing.JLabel jLabelEnterpriseType;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Panel panel1;
    private javax.swing.JTable tbl_Enterprise;
    private javax.swing.JTable tbl_Network;
    private javax.swing.JTextField txt_EnterpriseName;
    // End of variables declaration//GEN-END:variables
}
