/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NetworkAdminWorkArea;

import Business.Constants;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author praty
 */
public class ManageEnterpriseJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJpanel
     */
    public ManageEnterpriseJpanel() {
        initComponents();
    }

    JPanel userProcessContainer;
    Network network;
    UserAccount useraccount;
    Employee emp;
    Enterprise enterprise;
    public ManageEnterpriseJpanel(JPanel userProcessContainer,Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.network=network;        
        PopulateEnterpriseType();
    }
    
    public void PopulateEnterpriseType(){
        DropDown_EnterpriseType.removeAllItems();
        ArrayList<String> dupnterpriseType = new ArrayList<>();
        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            if(!dupnterpriseType.contains(type.getValue())){
                DropDown_EnterpriseType.addItem(type.getValue());
            }
            dupnterpriseType.add(type.getValue());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Enterprise = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        DropDown_EnterpriseType = new javax.swing.JComboBox();
        btn_update = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btn_Search = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbl_Enterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Enterprise Type", "Enterprise User Name", "Enterprise UserId"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_Enterprise);

        jLabel3.setText("Enterprise Type");

        DropDown_EnterpriseType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btn_update.setBackground(new java.awt.Color(255, 255, 255));
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/Save-as-icon.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/Go-back-icon.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/search-icon.png"))); // NOI18N
        btn_Search.setText("Search");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Images/Delete-icon.png"))); // NOI18N
        btn_Delete.setText("Delete");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(DropDown_EnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Search))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addGap(232, 232, 232)
                            .addComponent(btn_Delete)
                            .addGap(224, 224, 224)
                            .addComponent(btn_update))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(DropDown_EnterpriseType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Search))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Delete)
                        .addComponent(btn_update))
                    .addComponent(btnBack))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Enterprise");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        int selectedRow = tbl_Enterprise.getSelectedRow();

        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, Constants.Selectrow_tblEnterprise, "Error", JOptionPane.ERROR_MESSAGE);
        } else
        {
            if(tbl_Enterprise.getValueAt(selectedRow, 3).equals("")){
                JOptionPane.showMessageDialog(null, "There is no Admin present for this Enterprise to Update", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                enterprise = (Enterprise)tbl_Enterprise.getValueAt(selectedRow, 0);
                useraccount = (UserAccount)tbl_Enterprise.getValueAt(selectedRow, 3);
                UpdateEnterpriseJpanel UpdateEnterprise = new UpdateEnterpriseJpanel(userProcessContainer, network, enterprise,useraccount);
                userProcessContainer.add("UpdateEnterpriseJpanel", UpdateEnterprise);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
      int selectedRow = tbl_Enterprise.getSelectedRow();
        
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, Constants.Selectrow_tblEnterprise, "Error", JOptionPane.ERROR_MESSAGE);
        } else
        {
            try{
                enterprise = (Enterprise)tbl_Enterprise.getValueAt(selectedRow, 0);
                if(!tbl_Enterprise.getValueAt(selectedRow, 3).equals("")){
                   useraccount = (UserAccount)tbl_Enterprise.getValueAt(selectedRow, 3);
                }
                if(!tbl_Enterprise.getValueAt(selectedRow, 2).equals("")){
                    emp = (Employee)tbl_Enterprise.getValueAt(selectedRow, 2);
                }
                int selectionButton = JOptionPane.YES_NO_OPTION;
                int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete Network?? It will also delete Network Admin...","Warning",selectionButton);
                if(selectionResult == JOptionPane.YES_OPTION){
                    if(!tbl_Enterprise.getValueAt(selectedRow, 3).equals("")){
                       enterprise.getEmployeeDirectory().deleteEmployee(emp); 
                    }
                    if(!tbl_Enterprise.getValueAt(selectedRow, 2).equals("")){
                        enterprise.getUserAccountDirectory().deleteUserAccount(useraccount);
                    }
                    network.deleteEnterprise(enterprise);
                    PopulateEnterpriseTable();
                    PopulateEnterpriseType();
                }
            }
            catch(IndexOutOfBoundsException IO){
                JOptionPane.showMessageDialog(null, "Cannot Delete the Enterprise", "Error", JOptionPane.ERROR_MESSAGE);
            }
            catch(NullPointerException n){
                JOptionPane.showMessageDialog(null, "Cannot Delete the Enterprise", "Error", JOptionPane.ERROR_MESSAGE);
            }
            catch(RuntimeException re){
                JOptionPane.showMessageDialog(null, "Cannot Delete the Enterprise", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       userProcessContainer.remove(this);
       CardLayout layout = (CardLayout)userProcessContainer.getLayout();
       layout.previous(userProcessContainer); 
    }//GEN-LAST:event_btnBackActionPerformed

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        PopulateEnterpriseTable();
    }//GEN-LAST:event_btn_SearchActionPerformed

    
    private void PopulateEnterpriseTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_Enterprise.getModel();

        model.setRowCount(0);
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            if(enterprise.getEnterpriseType().getValue().equals(DropDown_EnterpriseType.getSelectedItem().toString())){
                for(UserAccount useracount : enterprise.getUserAccountDirectory().getUserAccountList()){
                    Object[] row = new Object[model.getColumnCount()];
                    row[0] = enterprise;
                    row[1] = enterprise.getEnterpriseType().getValue();
                    row[2] = useracount.getEmployee();
                    row[3] = useracount;
                    model.addRow(row);
                }
                if(enterprise.getUserAccountDirectory().getUserAccountList().isEmpty()){
                    Object[] row = new Object[model.getColumnCount()];
                    row[0] = enterprise;
                    row[1] = enterprise.getEnterpriseType().getValue();
                    row[2] = "";
                    row[3] = "";
                    model.addRow(row);
                }
            }   
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox DropDown_EnterpriseType;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Enterprise;
    // End of variables declaration//GEN-END:variables
}
